# Form implementation generated from reading ui file 'ui/add_crypto.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db import Database
db = Database('DataAnd.db')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(400, 200)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.crypto_buy_text = QtWidgets.QLabel(parent=self.centralwidget)
        self.crypto_buy_text.setGeometry(QtCore.QRect(60, 0, 291, 91))
        font = QtGui.QFont()
        font.setPointSize(20)
        self.crypto_buy_text.setFont(font)
        self.crypto_buy_text.setObjectName("crypto_buy_text")
        self.name_crypto_edit = QtWidgets.QLineEdit(parent=self.centralwidget)
        self.name_crypto_edit.setGeometry(QtCore.QRect(170, 100, 71, 25))
        self.name_crypto_edit.setObjectName("name_crypto_edit")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(120, 140, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 400, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        ##########################################3
        self.addFunction()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.crypto_buy_text.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\">Введите название </p><p align=\"center\">криптовалюты.</p></body></html>"))

    def addFunction(self):
        self.buttonBox.accepted.connect(lambda:self.addCrypto())
        self.buttonBox.rejected.connect(lambda:MainWindow.close())

    def addCrypto(self):
        db.set_crypto(self.name_crypto_edit.text(), 0, 'add')
        self.name_crypto_edit.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
