# Form implementation generated from reading ui file 'ui/add_card.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db import Database
db = Database('DataAnd.db')

class Ui_Add_card(object):
    def setupUi(self, Add_card):
        Add_card.setObjectName("Add_card")
        Add_card.resize(393, 180)
        self.centralwidget = QtWidgets.QWidget(parent=Add_card)
        self.centralwidget.setObjectName("centralwidget")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 20, 371, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.crypto_buy_text = QtWidgets.QLabel(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.crypto_buy_text.setFont(font)
        self.crypto_buy_text.setObjectName("crypto_buy_text")
        self.horizontalLayout.addWidget(self.crypto_buy_text)
        self.name_bank_edit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        self.name_bank_edit.setObjectName("name_bank_edit")
        self.horizontalLayout.addWidget(self.name_bank_edit)
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(210, 140, 171, 32))
        self.buttonBox.setOrientation(QtCore.Qt.Orientation.Horizontal)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget_2 = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget_2.setGeometry(QtCore.QRect(10, 80, 371, 34))
        self.layoutWidget_2.setObjectName("layoutWidget_2")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.layoutWidget_2)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.crypto_buy_text_2 = QtWidgets.QLabel(parent=self.layoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(20)
        self.crypto_buy_text_2.setFont(font)
        self.crypto_buy_text_2.setObjectName("crypto_buy_text_2")
        self.horizontalLayout_2.addWidget(self.crypto_buy_text_2)
        self.number_card_edit = QtWidgets.QLineEdit(parent=self.layoutWidget_2)
        self.number_card_edit.setObjectName("number_card_edit")
        self.horizontalLayout_2.addWidget(self.number_card_edit)
        Add_card.setCentralWidget(self.centralwidget)

        self.retranslateUi(Add_card)
        QtCore.QMetaObject.connectSlotsByName(Add_card)

        ###########################
        self.addFunction()

    def retranslateUi(self, Add_card):
        _translate = QtCore.QCoreApplication.translate
        Add_card.setWindowTitle(_translate("Add_card", "MainWindow"))
        self.crypto_buy_text.setText(_translate("Add_card", "<html><head/><body><p>Название банка: </p></body></html>"))
        self.crypto_buy_text_2.setText(_translate("Add_card", "<html><head/><body><p>Номер карты: </p></body></html>"))

    def addFunction(self):
        self.buttonBox.accepted.connect(lambda:self.accept())
        self.buttonBox.rejected.connect(lambda:Add_card.close())

    '''TAB_1'''

    def accept(self):
        if self.name_bank_edit.text() != "" and self.number_card_edit.text() != "":
            db.add_card(self.name_bank_edit.text(), self.number_card_edit.text())
            self.name_bank_edit.setText('')
            self.number_card_edit.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Add_card = QtWidgets.QMainWindow()
    ui = Ui_Add_card()
    ui.setupUi(Add_card)
    Add_card.show()
    sys.exit(app.exec())
