# Form implementation generated from reading ui file 'ui/change_window.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db import Database
import tools
db = Database('DataAnd.db')

class Ui_change_window(object):
    def setupUi(self, change_window):
        change_window.setObjectName("change_window")
        change_window.resize(315, 166)
        self.centralwidget = QtWidgets.QWidget(parent=change_window)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 311, 141))
        self.widget.setObjectName("widget")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_5.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.comboBox = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox.setObjectName("comboBox")
        self.verticalLayout.addWidget(self.comboBox)
        self.verticalLayout_3.addLayout(self.verticalLayout)
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_3.addWidget(self.label_2)
        self.horizontalLayout.addLayout(self.verticalLayout_3)
        self.verticalLayout_4 = QtWidgets.QVBoxLayout()
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.comboBox_2 = QtWidgets.QComboBox(parent=self.widget)
        self.comboBox_2.setObjectName("comboBox_2")
        self.verticalLayout_2.addWidget(self.comboBox_2)
        self.verticalLayout_4.addLayout(self.verticalLayout_2)
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.verticalLayout_4.addWidget(self.label_3)
        self.horizontalLayout.addLayout(self.verticalLayout_4)
        self.verticalLayout_5.addLayout(self.horizontalLayout)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.verticalLayout_5.addWidget(self.lineEdit)
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.verticalLayout_5.addWidget(self.pushButton)
        change_window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=change_window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 315, 22))
        self.menubar.setObjectName("menubar")
        change_window.setMenuBar(self.menubar)

        self.retranslateUi(change_window)
        QtCore.QMetaObject.connectSlotsByName(change_window)
        
        ################################
        self.addFunction()

    def retranslateUi(self, change_window):
        _translate = QtCore.QCoreApplication.translate
        change_window.setWindowTitle(_translate("change_window", "MainWindow"))
        self.label_2.setText(_translate("change_window", "<html><head/><body><p><span style=\" font-size:18pt;\">0</span></p></body></html>"))
        self.label_3.setText(_translate("change_window", "<html><head/><body><p><span style=\" font-size:18pt;\">0</span></p></body></html>"))
        self.pushButton.setText(_translate("change_window", "Обменять"))

        ##############################
        cryptos = db.get_all_elements('crypto', 'name_crypto')

        for item in cryptos:
            self.comboBox.addItem(item)
            self.comboBox_2.addItem(item)

    def addFunction(self):
        self.pushButton.clicked.connect(lambda:self.change())
        self.comboBox.currentIndexChanged.connect(lambda:self.set_balance('from'))
        self.comboBox_2.currentIndexChanged.connect(lambda:self.set_balance('to'))

    def change(self):
        if tools.contains_only_digits(self.lineEdit.text()) or tools.contains_only_digits(self.lineEdit.text()):
            print(self.lineEdit.text())
            
    def set_balance(self, meaning):
        if meaning == 'from':
            pass
        elif meaning == 'to':
            pass

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    change_window = QtWidgets.QMainWindow()
    ui = Ui_change_window()
    ui.setupUi(change_window)
    change_window.show()
    sys.exit(app.exec())
