# Form implementation generated from reading ui file 'ui/change_menu.ui'
#
# Created by: PyQt6 UI code generator 6.5.3
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
from db import Database
import tools
db = Database('DataAnd.db')

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(350, 120)
        self.centralwidget = QtWidgets.QWidget(parent=MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.status_label = QtWidgets.QLabel(parent=self.centralwidget)
        self.status_label.setGeometry(QtCore.QRect(170, 70, 171, 20))
        self.status_label.setObjectName("status_label")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 151, 79))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.from_crypto = QtWidgets.QComboBox(parent=self.widget)
        self.from_crypto.setObjectName("from_crypto")
        self.verticalLayout.addWidget(self.from_crypto)
        self.to_crypto = QtWidgets.QComboBox(parent=self.widget)
        self.to_crypto.setObjectName("to_crypto")
        self.verticalLayout.addWidget(self.to_crypto)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.pushButton = QtWidgets.QPushButton(parent=self.widget)
        self.pushButton.setObjectName("pushButton")
        self.horizontalLayout.addWidget(self.pushButton)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.widget1 = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget1.setGeometry(QtCore.QRect(170, 10, 170, 16))
        self.widget1.setObjectName("widget1")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget1)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(parent=self.widget1)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.label_2 = QtWidgets.QLabel(parent=self.widget1)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 350, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)


        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

        self.addFunctional()

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.status_label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:14pt;\">TextLabel</span></p></body></html>"))
        self.pushButton.setText(_translate("MainWindow", "Обменять"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">Текущий курс:</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:9pt;\">0</span></p></body></html>"))

        cryptos = db.get_all_elements('crypto', 'name_crypto')

        self.from_crypto.addItems(cryptos)
        self.to_crypto.addItems(cryptos)

    def addFunctional(self):
        self.pushButton.clicked.connect(lambda:self.change_crypto())
    
    def change_crypto(self):
        from_crypto = self.from_crypto.currentText()
        to_crypto = self.to_crypto.currentText()

        if tools.contains_only_digits(self.lineEdit.text()) and from_crypto != to_crypto:
            res = tools.change_money(from_crypto, to_crypto, self.lineEdit.text())
            print(res['retMsg'])
            try:
                if res['retMsg'] == "Insufficient balance.":
                    self.status_label.setText("Недостаточно средств.")
                elif res['retMsg'] == "Order value exceeded lower limit.":
                    self.status_label.setText("Маленькая заявка.")
            except:
                pass
        


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec())
