# Form implementation generated from reading ui file 'ui/connect_api.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import tools
from db import Database
db = Database('DataAnd.db')

class Ui_connect_api(object):
    def setupUi(self, connect_api):
        connect_api.setObjectName("connect_api")
        connect_api.resize(392, 177)
        self.centralwidget = QtWidgets.QWidget(parent=connect_api)
        self.centralwidget.setObjectName("centralwidget")
        self.checkBox = QtWidgets.QCheckBox(parent=self.centralwidget)
        self.checkBox.setGeometry(QtCore.QRect(20, 110, 141, 31))
        self.checkBox.setObjectName("checkBox")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(180, 110, 169, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 10, 361, 91))
        self.widget.setObjectName("widget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.widget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit.setText("")
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_2 = QtWidgets.QLabel(parent=self.widget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        self.lineEdit_2.setText("")
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        connect_api.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=connect_api)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 392, 22))
        self.menubar.setObjectName("menubar")
        connect_api.setMenuBar(self.menubar)

        self.retranslateUi(connect_api)
        QtCore.QMetaObject.connectSlotsByName(connect_api)

        ###########################
        self.addFunction()

    def retranslateUi(self, connect_api):
        _translate = QtCore.QCoreApplication.translate
        connect_api.setWindowTitle(_translate("connect_api", "MainWindow"))
        self.checkBox.setToolTip(_translate("connect_api", "<html><head/><body><p><span style=\" font-size:20pt;\">Поключиться</span></p></body></html>"))
        self.checkBox.setText(_translate("connect_api", "Подключиться"))
        self.label.setText(_translate("connect_api", "<html><head/><body><p><span style=\" font-size:20pt;\">API KEY</span></p></body></html>"))
        self.label_2.setText(_translate("connect_api", "<html><head/><body><p><span style=\" font-size:20pt;\">API SECRET</span></p></body></html>"))
        self.lineEdit.setText(f"{db.get_from_config('api_key')}") if db.get_from_config('api_key') != None else None
        self.lineEdit_2.setText(f"{db.get_from_config('api_secret')}") if db.get_from_config('api_secret') != None else None
        self.checkBox.setChecked(db.get_from_config('isWorkAPI'))

    def addFunction(self):
        self.buttonBox.accepted.connect(lambda:self.accept())
        self.buttonBox.rejected.connect(lambda:connect_api.close())
        self.checkBox.stateChanged.connect(lambda:db.write_in_config(['isWorkAPI', True]) if self.checkBox.isChecked() else db.write_in_config(['isWorkAPI', False]))
    
    def accept(self):
        db.write_in_config(['api_key', self.lineEdit.text()])
        db.write_in_config(['api_secret', self.lineEdit_2.text()])
        connect_api.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    connect_api = QtWidgets.QMainWindow()
    ui = Ui_connect_api()
    ui.setupUi(connect_api)
    connect_api.show()
    sys.exit(app.exec())
