# Form implementation generated from reading ui file 'end_session.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import tools
from db import Database

db = Database("DataAnd.db")

class Ui_End_session_Window(object):
    def setupUi(self, End_session_Window):
        End_session_Window.setObjectName("End_session_Window")
        End_session_Window.resize(455, 226)
        self.centralwidget = QtWidgets.QWidget(parent=End_session_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(100, 0, 241, 61))
        self.label.setObjectName("label")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(70, 70, 301, 41))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label_2 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_2.setObjectName("label_2")
        self.horizontalLayout.addWidget(self.label_2)
        self.label_3 = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label_3.setBaseSize(QtCore.QSize(0, 0))
        self.label_3.setObjectName("label_3")
        self.horizontalLayout.addWidget(self.label_3)
        self.pushButton = QtWidgets.QPushButton(parent=self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(160, 140, 131, 41))
        self.pushButton.setObjectName("pushButton")
        End_session_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=End_session_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 455, 22))
        self.menubar.setObjectName("menubar")
        End_session_Window.setMenuBar(self.menubar)

        self.retranslateUi(End_session_Window)
        QtCore.QMetaObject.connectSlotsByName(End_session_Window)

        ############################
        self.addFunction()

    def retranslateUi(self, End_session_Window):
        _translate = QtCore.QCoreApplication.translate
        End_session_Window.setWindowTitle(_translate("End_session_Window", "MainWindow"))

        summ = sum(db.get_all_elements('cards', 'balance'))
        print(summ)

        self.label.setText(_translate("End_session_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:28pt;\">Конец сессии</span></p></body></html>"))
        self.label_2.setText(_translate("End_session_Window", "<html><head/><body><p><span style=\" font-size:22pt;\">Заработанно:</span></p></body></html>"))
        self.label_3.setText(_translate("End_session_Window", f"<html><head/><body><p align=\"right\"><span style=\" font-size:22pt;\">{summ - db.get_from_config('balance')}</span></p></body></html>"))
        self.pushButton.setText(_translate("End_session_Window", "Сохранить отчёт"))

    def addFunction(self):
        self.pushButton.clicked.connect(lambda:self.save_statistic())

    def save_statistic(self):
        End_session_Window.close()

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    End_session_Window = QtWidgets.QMainWindow()
    ui = Ui_End_session_Window()
    ui.setupUi(End_session_Window)
    End_session_Window.show()
    sys.exit(app.exec())
