# Form implementation generated from reading ui file 'start_session.ui'
#
# Created by: PyQt6 UI code generator 6.5.2
#
# WARNING: Any manual changes made to this file will be lost when pyuic6 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt6 import QtCore, QtGui, QtWidgets
import tools
from db import Database
db = Database('DataAnd.db')

class Ui_Start_Session_Window(object):
    def setupUi(self, Start_Session_Window):
        Start_Session_Window.setObjectName("Start_Session_Window")
        Start_Session_Window.resize(506, 316)
        self.centralwidget = QtWidgets.QWidget(parent=Start_Session_Window)
        self.centralwidget.setObjectName("centralwidget")
        self.label_2 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(80, 0, 341, 71))
        self.label_2.setObjectName("label_2")
        self.buttonBox = QtWidgets.QDialogButtonBox(parent=self.centralwidget)
        self.buttonBox.setGeometry(QtCore.QRect(330, 260, 171, 31))
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.StandardButton.Cancel|QtWidgets.QDialogButtonBox.StandardButton.Ok)
        self.buttonBox.setObjectName("buttonBox")
        self.layoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.layoutWidget.setGeometry(QtCore.QRect(10, 90, 481, 34))
        self.layoutWidget.setObjectName("layoutWidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.layoutWidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(parent=self.layoutWidget)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        self.lineEdit = QtWidgets.QLineEdit(parent=self.layoutWidget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit.setFont(font)
        self.lineEdit.setObjectName("lineEdit")
        self.horizontalLayout.addWidget(self.lineEdit)
        self.choose_card_box = QtWidgets.QComboBox(parent=self.centralwidget)
        self.choose_card_box.setGeometry(QtCore.QRect(10, 200, 221, 25))
        self.choose_card_box.setObjectName("choose_card_box")
        self.name_bank = QtWidgets.QLabel(parent=self.centralwidget)
        self.name_bank.setGeometry(QtCore.QRect(250, 200, 217, 31))
        self.name_bank.setObjectName("name_bank")
        self.write_balance_card_btn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.write_balance_card_btn.setGeometry(QtCore.QRect(50, 240, 121, 41))
        self.write_balance_card_btn.setObjectName("write_balance_card_btn")
        self.widget = QtWidgets.QWidget(parent=self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(10, 150, 481, 34))
        self.widget.setObjectName("widget")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout(self.widget)
        self.horizontalLayout_2.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label_3 = QtWidgets.QLabel(parent=self.widget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_2.addWidget(self.label_3)
        self.lineEdit_2 = QtWidgets.QLineEdit(parent=self.widget)
        font = QtGui.QFont()
        font.setPointSize(16)
        self.lineEdit_2.setFont(font)
        self.lineEdit_2.setObjectName("lineEdit_2")
        self.horizontalLayout_2.addWidget(self.lineEdit_2)
        Start_Session_Window.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=Start_Session_Window)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 506, 22))
        self.menubar.setObjectName("menubar")
        Start_Session_Window.setMenuBar(self.menubar)

        self.retranslateUi(Start_Session_Window)
        QtCore.QMetaObject.connectSlotsByName(Start_Session_Window)

        self.retranslateUi(Start_Session_Window)
        QtCore.QMetaObject.connectSlotsByName(Start_Session_Window)

        ############################
        self.addFunction()

    def retranslateUi(self, Start_Session_Window):
        _translate = QtCore.QCoreApplication.translate
        Start_Session_Window.setWindowTitle(_translate("Start_Session_Window", "MainWindow"))
        self.label_2.setText(_translate("Start_Session_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:36pt;\">Начать сессию</span></p></body></html>"))
        self.label.setText(_translate("Start_Session_Window", "<html><head/><body><p><span style=\" font-size:20pt;\">Стартовый баланс:</span></p></body></html>"))
        self.name_bank.setText(_translate("Start_Session_Window", "<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">Банк</span></p></body></html>"))
        self.write_balance_card_btn.setText(_translate("Start_Session_Window", "Сделать запись"))
        self.label_3.setText(_translate("Start_Session_Window", "<html><head/><body><p><span style=\" font-size:20pt;\">Баланс на карте: </span></p></body></html>"))
        self.choose_card_box.clear()

        for item in db.get_all_elements('cards', 'number_card'):
            self.choose_card_box.addItem(item)
        self.name_bank.setText(_translate("Start_Session_Windows", f"<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">{db.find_element('cards', ['number_card', self.choose_card_box.currentText()], 'name_bank')}</span></p></body></html>"))

    def addFunction(self):
        _translate = QtCore.QCoreApplication.translate
        self.buttonBox.accepted.connect(lambda:self.set_config())
        self.buttonBox.rejected.connect(lambda:Start_Session_Window.close())
        self.choose_card_box.currentIndexChanged.connect(lambda:self.name_bank.setText(_translate("Start_Session_Windows", f"<html><head/><body><p align=\"center\"><span style=\" font-size:20pt;\">{db.find_element('cards', ['number_card', self.choose_card_box.currentText()], 'name_bank')}</span></p></body></html>")))
        self.write_balance_card_btn.clicked.connect(lambda:self.write_bank())

    def set_config(self):
        if tools.contains_only_digits(self.lineEdit.text()):
            tools.update_csv_cell('data/config.csv', 0, 0, self.lineEdit.text()), Start_Session_Window.close() if tools.contains_only_digits(self.lineEdit.text()) else print('no')
            self.lineEdit.setText('')

    def write_bank(self):
        balance = self.lineEdit_2.text()
        if balance != "" and tools.contains_only_digits(self.lineEdit_2.text()):
            db.set_balance(self.choose_card_box.currentText(), float(balance), 'set')
            self.lineEdit_2.setText('')

if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Start_Session_Window = QtWidgets.QMainWindow()
    ui = Ui_Start_Session_Window()
    ui.setupUi(Start_Session_Window)
    Start_Session_Window.show()
    sys.exit(app.exec())
